version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: edgevision-backend
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - MONGODB_URI=mongodb+srv://rdxsparrowgaming_db_user:DBL67D8Qc0RcqlCf@cluster0.er22sa5.mongodb.net/?appName=Cluster0
    volumes:
      - ./models:/app/models
      - ./experiments:/app/experiments
      - ./datasets:/app/datasets
      - ./database:/app/database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: edgevision-frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
