/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CamerasRouteImport } from './routes/cameras'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ModelRouteImport } from './routes/model'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TestRouteImport } from './routes/test'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as ZonesRouteImport } from './routes/zones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasRoute = CamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cameras': typeof CamerasRoute
  '/compliance': typeof ComplianceRoute
  '/live': typeof LiveRoute
  '/model': typeof ModelRoute
  '/reports': typeof ReportsRoute
  '/test': typeof TestRoute
  '/violations': typeof ViolationsRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cameras': typeof CamerasRoute
  '/compliance': typeof ComplianceRoute
  '/live': typeof LiveRoute
  '/model': typeof ModelRoute
  '/reports': typeof ReportsRoute
  '/test': typeof TestRoute
  '/violations': typeof ViolationsRoute
  '/zones': typeof ZonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cameras': typeof CamerasRoute
  '/compliance': typeof ComplianceRoute
  '/live': typeof LiveRoute
  '/model': typeof ModelRoute
  '/reports': typeof ReportsRoute
  '/test': typeof TestRoute
  '/violations': typeof ViolationsRoute
  '/zones': typeof ZonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cameras'
    | '/compliance'
    | '/live'
    | '/model'
    | '/reports'
    | '/test'
    | '/violations'
    | '/zones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cameras'
    | '/compliance'
    | '/live'
    | '/model'
    | '/reports'
    | '/test'
    | '/violations'
    | '/zones'
  id:
    | '__root__'
    | '/'
    | '/cameras'
    | '/compliance'
    | '/live'
    | '/model'
    | '/reports'
    | '/test'
    | '/violations'
    | '/zones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CamerasRoute: typeof CamerasRoute
  ComplianceRoute: typeof ComplianceRoute
  LiveRoute: typeof LiveRoute
  ModelRoute: typeof ModelRoute
  ReportsRoute: typeof ReportsRoute
  TestRoute: typeof TestRoute
  ViolationsRoute: typeof ViolationsRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras': {
      id: '/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof CamerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CamerasRoute: CamerasRoute,
  ComplianceRoute: ComplianceRoute,
  LiveRoute: LiveRoute,
  ModelRoute: ModelRoute,
  ReportsRoute: ReportsRoute,
  TestRoute: TestRoute,
  ViolationsRoute: ViolationsRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
